# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# Then, it will push new versions to pycromanager

name: Update NDTiff in pycromanager

on:
  push:
    branches:
      - main
    paths:
       - 'java/pom.xml'

jobs:
  update-pycromanger:
    needs: maven-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout-PM
      uses: actions/checkout@v3
      with:
        path: 'pycro-manager'
        repository: micro-manager/pycro-manager
        ref: dependencies
        fetch-depth: 0 # check out all branches
        token: ${{ secrets.PYCRO_TOKEN }}
    - name: Checkout-ND
      uses: actions/checkout@v3
      with:
        path: 'NDTiffStorage'
        repository: micro-manager/NDTiffStorage
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: update-version
      run: |
        cd pycro-manager
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "NDTiff-Bot"
        # fast forward to get code updates on main branch
        git merge origin/main -m "dependency update merge"
        python update_ndtiff.py
    - name: commit
      run: |
        cd pycro-manager
        git commit -am "update NDTiff version"
    - name: push
      run: |
        cd pycro-manager
        git push https://henrypinkard:${{ secrets.PYCRO_TOKEN }}@github.com/micro-manager/pycro-manager.git  

        
